#!/bin/sh
### BEGIN INIT INFO
# Provides:				dyn53
# Required-Start:		$network
# Required-Stop:		$network
# Default-Start:		3 4 5
# Default-Stop:			0 1 2 6
# Short-Description:	Dyn53
# Description:			Dynamic DNS client for Amazon Route 53
### END INIT INFO
# Copyright 2015 Philip Cronje
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
DYN53_LOG_FILE=/var/log/dyn53/dyn53.log
DYN53_PID_DIR=/var/run/dyn53
DYN53_PID_FILE=$DYN53_PID_DIR/dyn53.pid
DYN53_USER=dyn53

# Uncomment and supply values for the following two variables
# DYN53_HOSTED_ZONE_ID=
# DYN53_RESOURCE_RECORD_SET_NAME=
# DYN53_JAR_FILE=
# JAVA_BIN=

. /lib/lsb/init-functions

do_start() {
	log_daemon_msg "Starting Dyn53" "dyn53"
	if [ ! -d $DYN53_PID_DIR ]; then
		mkdir -p $DYN53_PID_DIR
		chown $DYN53_USER: $DYN53_PID_DIR
		chmod 0755 $DYN53_PID_DIR
	fi
	if start-stop-daemon --start --chuid $DYN53_USER --quiet --pidfile $DYN53_PID_FILE --background \
			--exec $JAVA_BIN -- -Dnet.za.slyfox.dyn53.route53.hostedZoneId=$DYN53_HOSTED_ZONE_ID \
			-Dnet.za.slyfox.dyn53.route53.resourceRecordSetName=$DYN53_RESOURCE_RECORD_SET_NAME \
			-Dnet.za.slyfox.dyn53.daemon.pidFile=$DYN53_PID_FILE \
			-Dnet.za.slyfox.dyn53.logFile=$DYN53_LOG_FILE \
			-jar $DYN53_JAR_FILE; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

do_stop() {
	log_daemon_msg "Stopping Dyn53" "dyn53"
	if start-stop-daemon --stop --retry 10 --quiet --pidfile $DYN53_PID_FILE --user $DYN53_USER; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart|force-reload)
		do_stop
		do_start
		;;
	status)
		status_of_proc -p $DYN53_PID_FILE java dyn53 && exit 0 || exit $?
		;;
	*)
		log_action_msg "Usage: $0 {start|stop|restart|force-reload|status}"
		exit 3
		;;
esac
:
# vim: set ts=4 sw=4 noet:
